steps:
- name: 'ubuntu'
  args: ["printenv", ">", ".env"]
  env:
    - 'REACT_APP_LOGIN_SK=${_LOGIN_SK}'
    - 'REACT_APP_LOGIN_ID=${_LOGIN_ID}'
    - 'REACT_APP_LOGIN_ENDPOINT=${_LOGIN_ENDPOINT}'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cmu_lost_and_found/image', '.']