steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'REACT_APP_LOGIN_SK="${_LOGIN_SK}"'
  - '--build-arg'
  - 'REACT_APP_LOGIN_ID="${_LOGIN_ID}"'
  - '--build-arg'
  - 'REACT_APP_LOGIN_ENDPOINT="${_LOGIN_ENDPOINT}"'
  - '-t'
  - 'gcr.io/cmu_lost_and_found/image'
  - '.'